// Database types - auto-generated by Supabase CLI or manually defined
// Run `npx supabase gen types typescript --project-id YOUR_PROJECT_ID` to generate

import { Payment } from './types';

export interface User {
  id: string;
  created_at: string;
  company_name: string;
  email: string;
  wallet_address: string;
  type: 'buyer' | 'seller' | 'lender';
  privy_user_id: string;
}

export interface LenderPosition {
  id: string;
  created_at: string;
  offer_id: string;
  lender_address: string;
  amount: string;
  discount_rate: number; // 5 or 10
  amount_available: string;
  amount_lent: string;
  status: 'active' | 'withdrawn' | 'fully_deployed';
  updated_at: string;
}

export interface FactoredInvoice {
  id: string;
  created_at: string;
  payment_id: string;
  seller_address: string;
  lender_offer_id: string;
  invoice_id: string; // bytes32 hash
  total_invoice_amount: string;
  upfront_paid: string;
  factored_amount: string;
  payout_to_seller: string;
  discount_rate: number; // 5 or 10
  status: 'pending' | 'matched' | 'settled' | 'failed';
  tx_hash: string | null;
  updated_at: string;
}

export interface Database {
  public: {
    Tables: {
      payments: {
        Row: Payment;
        Insert: Omit<Payment, 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<Payment, 'id' | 'created_at'>> & {
          updated_at?: string;
        };
        Relationships: [];
      };
      users: {
        Row: User;
        Insert: Omit<User, 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Omit<User, 'id' | 'created_at'>> & {
          created_at?: string;
        };
        Relationships: [];
      };
      lender_positions: {
        Row: LenderPosition;
        Insert: Omit<LenderPosition, 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<LenderPosition, 'id' | 'created_at'>> & {
          updated_at?: string;
        };
        Relationships: [];
      };
      factored_invoices: {
        Row: FactoredInvoice;
        Insert: Omit<FactoredInvoice, 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<FactoredInvoice, 'id' | 'created_at'>> & {
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'factored_invoices_payment_id_fkey';
            columns: ['payment_id'];
            referencedRelation: 'payments';
            referencedColumns: ['id'];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
