// Database types - auto-generated by Supabase CLI or manually defined
// Run `npx supabase gen types typescript --project-id YOUR_PROJECT_ID` to generate

import { Payment } from './types';

export interface Database {
  public: {
    Tables: {
      payments: {
        Row: Payment;
        Insert: Omit<Payment, 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<Payment, 'id' | 'created_at'>> & {
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
