// Database types - auto-generated by Supabase CLI or manually defined
// Run `npx supabase gen types typescript --project-id YOUR_PROJECT_ID` to generate

import { Payment } from './types';

export interface User {
  id: string;
  created_at: string;
  company_name: string;
  email: string;
  wallet_address: string;
  type: 'buyer' | 'seller';
  privy_user_id: string;
}

export interface Database {
  public: {
    Tables: {
      payments: {
        Row: Payment;
        Insert: Omit<Payment, 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<Payment, 'id' | 'created_at'>> & {
          updated_at?: string;
        };
        Relationships: [];
      };
      users: {
        Row: User;
        Insert: Omit<User, 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Omit<User, 'id' | 'created_at'>> & {
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
